In [1]:
import polars as pl

In [13]:
kpi = pl.read_parquet('fact_kpi_2026-09-09.parquet')
loss = pl.read_parquet('fact_loss_2026-09-09.parquet')
# kpi = pl.read_parquet(r"C:\WORK\IBM-RECKITT\ReportReplica\oee_sample_tables\fact_kpi\fact_kpi_2026-09-24.parquet")
# loss = pl.read_parquet(r"C:\WORK\IBM-RECKITT\ReportReplica\oee_sample_tables\fact_loss\fact_loss_2026-09-24.parquet")

In [14]:
kpi.filter(
    pl.col('asset_name').eq('GT4')
)

shape: (24, 45)
┌────────────┬────────────┬──────┬──────────┬───┬────────────┬────────────┬───────────┬────────────┐
│ asset_id   ┆ asset_name ┆ site ┆ area     ┆ … ┆ macro_stop ┆ missing_ma ┆ load_mode ┆ loaded_at  │
│ ---        ┆ ---        ┆ ---  ┆ ---      ┆   ┆ s_count    ┆ pping      ┆ ---       ┆ ---        │
│ str        ┆ str        ┆ str  ┆ str      ┆   ┆ ---        ┆ ---        ┆ str       ┆ datetime[m │
│            ┆            ┆      ┆          ┆   ┆ f64        ┆ str        ┆           ┆ s]         │
╞════════════╪════════════╪══════╪══════════╪═══╪════════════╪════════════╪═══════════╪════════════╡
│ bc08dae161 ┆ GT4        ┆ Hull ┆ Blisters ┆ … ┆ 0.0833     ┆ null       ┆ backfill  ┆ 2026-10-02 │
│ 124f1cb533 ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆ 08:03:42.0 │
│ 199f556190 ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆ 73         │
│ …          ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆            │
│ bc08dae161 ┆ GT4        ┆ Hull ┆ Blisters ┆ … ┆ 0.0833     ┆ null       ┆ backfill  ┆ 2026-10-02 │
│ 124f1cb533 ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆ 08:03:42.0 │
│ 199f556190 ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆ 73         │
│ …          ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆            │
│ bc08dae161 ┆ GT4        ┆ Hull ┆ Blisters ┆ … ┆ 0.0833     ┆ null       ┆ backfill  ┆ 2026-10-02 │
│ 124f1cb533 ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆ 08:03:42.0 │
│ 199f556190 ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆ 73         │
│ …          ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆            │
│ bc08dae161 ┆ GT4        ┆ Hull ┆ Blisters ┆ … ┆ 0.0833     ┆ null       ┆ backfill  ┆ 2026-10-02 │
│ 124f1cb533 ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆ 08:03:42.0 │
│ 199f556190 ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆ 73         │
│ …          ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆            │
│ bc08dae161 ┆ GT4        ┆ Hull ┆ Blisters ┆ … ┆ 0.0833     ┆ null       ┆ backfill  ┆ 2026-10-02 │
│ 124f1cb533 ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆ 08:03:42.0 │
│ 199f556190 ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆ 73         │
│ …          ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆            │
│ …          ┆ …          ┆ …    ┆ …        ┆ … ┆ …          ┆ …          ┆ …         ┆ …          │
│ bc08dae161 ┆ GT4        ┆ Hull ┆ Blisters ┆ … ┆ 0.4167     ┆ null       ┆ backfill  ┆ 2026-10-02 │
│ 124f1cb533 ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆ 08:03:42.0 │
│ 199f556190 ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆ 73         │
│ …          ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆            │
│ bc08dae161 ┆ GT4        ┆ Hull ┆ Blisters ┆ … ┆ 0.4167     ┆ null       ┆ backfill  ┆ 2026-10-02 │
│ 124f1cb533 ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆ 08:03:42.0 │
│ 199f556190 ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆ 73         │
│ …          ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆            │
│ bc08dae161 ┆ GT4        ┆ Hull ┆ Blisters ┆ … ┆ 0.4167     ┆ null       ┆ backfill  ┆ 2026-10-02 │
│ 124f1cb533 ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆ 08:03:42.0 │
│ 199f556190 ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆ 73         │
│ …          ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆            │
│ bc08dae161 ┆ GT4        ┆ Hull ┆ Blisters ┆ … ┆ 0.4167     ┆ null       ┆ backfill  ┆ 2026-10-02 │
│ 124f1cb533 ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆ 08:03:42.0 │
│ 199f556190 ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆ 73         │
│ …          ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆            │
│ bc08dae161 ┆ GT4        ┆ Hull ┆ Blisters ┆ … ┆ 0.0833     ┆ null       ┆ backfill  ┆ 2026-10-02 │
│ 124f1cb533 ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆ 08:03:42.0 │
│ 199f556190 ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆ 73         │
│ …          ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆            │
└────────────┴────────────┴──────┴──────────┴───┴────────────┴────────────┴───────────┴────────────┘

In [15]:
loss.filter(
    pl.col('asset_name').eq('GT4')
)

shape: (6, 23)
┌────────────┬────────────┬──────┬──────────┬───┬────────────┬────────────┬───────────┬────────────┐
│ asset_id   ┆ asset_name ┆ site ┆ area     ┆ … ┆ comment_co ┆ overwritte ┆ load_mode ┆ loaded_at  │
│ ---        ┆ ---        ┆ ---  ┆ ---      ┆   ┆ unt        ┆ n          ┆ ---       ┆ ---        │
│ str        ┆ str        ┆ str  ┆ str      ┆   ┆ ---        ┆ ---        ┆ str       ┆ datetime[m │
│            ┆            ┆      ┆          ┆   ┆ i64        ┆ bool       ┆           ┆ s]         │
╞════════════╪════════════╪══════╪══════════╪═══╪════════════╪════════════╪═══════════╪════════════╡
│ bc08dae161 ┆ GT4        ┆ Hull ┆ Blisters ┆ … ┆ 0          ┆ false      ┆ backfill  ┆ 2026-10-02 │
│ 124f1cb533 ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆ 08:03:42.0 │
│ 199f556190 ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆ 73         │
│ …          ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆            │
│ bc08dae161 ┆ GT4        ┆ Hull ┆ Blisters ┆ … ┆ 0          ┆ false      ┆ backfill  ┆ 2026-10-02 │
│ 124f1cb533 ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆ 08:03:42.0 │
│ 199f556190 ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆ 73         │
│ …          ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆            │
│ bc08dae161 ┆ GT4        ┆ Hull ┆ Blisters ┆ … ┆ 0          ┆ false      ┆ backfill  ┆ 2026-10-02 │
│ 124f1cb533 ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆ 08:03:42.0 │
│ 199f556190 ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆ 73         │
│ …          ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆            │
│ bc08dae161 ┆ GT4        ┆ Hull ┆ Blisters ┆ … ┆ 0          ┆ false      ┆ backfill  ┆ 2026-10-02 │
│ 124f1cb533 ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆ 08:03:42.0 │
│ 199f556190 ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆ 73         │
│ …          ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆            │
│ bc08dae161 ┆ GT4        ┆ Hull ┆ Blisters ┆ … ┆ 0          ┆ false      ┆ backfill  ┆ 2026-10-02 │
│ 124f1cb533 ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆ 08:03:42.0 │
│ 199f556190 ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆ 73         │
│ …          ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆            │
│ bc08dae161 ┆ GT4        ┆ Hull ┆ Blisters ┆ … ┆ 0          ┆ false      ┆ backfill  ┆ 2026-10-02 │
│ 124f1cb533 ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆ 08:03:42.0 │
│ 199f556190 ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆ 73         │
│ …          ┆            ┆      ┆          ┆   ┆            ┆            ┆           ┆            │
└────────────┴────────────┴──────┴──────────┴───┴────────────┴────────────┴───────────┴────────────┘